setwd("C:/Users/Екатерина/Documents/Интерсвязь/Тестовое задание")
library(RODBC)
ch1=odbcConnect("BD")
if (require(shiny)==F) install.packages('shiny', dependencies=T)
if (require(shinydashboard)==F) install.packages('shinydashboard', dependencies=T)
if (require(shinyTime)==F) install.packages('shinyTime', dependencies=T)
if (require(DT)==F) install.packages('DT', dependencies=T)
# library(shinyTime)
# library(DT)

# library(shinyjs)
# library(shinyBS)
# library(rpart)
# library(rpart.plot)
# library(shinyWidgets)
# library(rJava)
# library(XLConnectJars)
# library(XLConnect)
# library(shinyalert)
# require(lattice)
source("global.R")
# load("C:/Users/ar.khasanov/Desktop/SYSTEM_3.1/list_controllable.RData")
# load("C:/Users/ar.khasanov/Desktop/SYSTEM_3.1/list_uncontrollable.RData")
# smena=read.csv2("C:/Users/ar.khasanov/Desktop/Test/smena.csv", head=TRUE)
#runApp(appDir = getwd(),launch.browser = F, port=86)
runApp(appDir = getwd(),launch.browser = T,port=5600)
