getwd()
setwd("C:/Users/Екатерина/Documents/Интерсвязь/Тестовое задание")
if (require(RODBC)==F) install.packages('RODBC', dependencies=T)
ch1=odbcConnect("BD")
if (require(shiny)==F) install.packages('shiny', dependencies=T)
if (require(shinydashboard)==F) install.packages('shinydashboard', dependencies=T)
if (require(shinyTime)==F) install.packages('shinyTime', dependencies=T)
if (require(DT)==F) install.packages('DT', dependencies=T)
if (require(shinyBS)==F) install.packages('shinyBS', dependencies=T)
if (require(rJava)==F) install.packages('rJava', dependencies=T)
if (require(XLConnect)==F) install.packages('XLConnect', dependencies=T)
if (require(XLConnectJars)==F) install.packages('XLConnectJars', dependencies=T)
source("global.R")
runApp(appDir = getwd(),launch.browser = T,port=5600)
